### DISCUSSION TITLE
How can I convert a simple nginx docker-compose to systemd quadlet on bluefin-dx?

### DISCUSSION THREAD

**Discussion by lazypower** [ublue-os/bluefin#2264] [Dosu Help Section]
@dosu I've read that systemd-quadlets are natively supported on linux systems with podman. How can I convert the following docker-compose to a quadlet? 

```yaml
services:
  nginx:
    image: docker.io/nginx:latest
    ports:
      - 8080:80
    volumes:
      - nginx-static-site:/usr/share/nginx/html
```
