### ISSUE TITLE
k0s

### ISSUE THREAD

**Issue by hanthor** [ublue-os/bluefin#2303]
### Describe the package

Seeting up a k0s cluster on Bluefin. maybe via ujust

### Image

All Images

**Comment by hanthor** [comment]
Setting up a k0s cluaster on 2 bluefin computers

had to add the tailscale IPs and the specify the tailscale interface
```
apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
  user: admin
spec:
  hosts:
  - ssh:
      address: 100.x.x.x
      user: james
      port: 22
      keyPath: null
    privateInterface: tailscale0
    role: controller
  - ssh:
      address: 100.x.x.x
      user: james
      port: 22
      keyPath: /var/home/james/.ssh/id_ed25519
    privateInterface: tailscale0
    role: worker
```

Controller nodes:
```
# Allow etcd peer communication (controller <-> controller)
sudo firewall-cmd --permanent --add-port=2380/tcp

# Allow Kube API Server access (worker/CLI -> controller)
sudo firewall-cmd --permanent --add-port=6443/tcp

# Allow Kubelet API access (controller -> kubelet on controllers/workers)
# Although the Kubelet runs on all nodes, the API Server on the controller needs to reach it.
sudo firewall-cmd --permanent --add-port=10250/tcp

# Allow k0s controller join API (controller <-> controller)
sudo firewall-cmd --permanent --add-port=9443/tcp

# Allow Konnectivity server access (worker -> controller)
sudo firewall-cmd --permanent --add-port=8132/tcp
sudo firewall-cmd --permanent --add-port=8133/tcp

sudo firewall-cmd --reload
```
Worker nodes:
```
# Allow Kubelet API access (controller -> kubelet on workers)
sudo firewall-cmd --permanent --add-port=10250/tcp

# Option 1: If using kube-router (BGP)
# Allow BGP traffic (worker <-> worker)
sudo firewall-cmd --permanent --add-port=179/tcp

# Option 2: If using Calico (VXLAN)
# Allow Calico VXLAN traffic (worker <-> worker)
sudo firewall-cmd --permanent --add-port=4789/udp


# Apply the rules immediately
sudo firewall-cmd --reload
```
